SELECT * FROM Suppliers;
SELECT BirthDate, FirstName, LastName FROM Employees;
SELECT * FROM Employees WHERE BirthDate LIKE "1958%";
SELECT * FROM Products WHERE Price between 15 AND 40;
SELECT min(Price) FROM Products;
SELECT max(Price) FROM Products;
SELECT * FROM Products WHERE Unit = "24 - 12 oz bottles" ORDER BY Price DESC;
SELECT SupplierName FROM Suppliers WHERE City = "Tokyo" OR City = "Frankfurt" OR City = "Osaka";
SELECT SupplierName FROM Suppliers WHERE City IN ("Tokyo", "Frankfurt", "Osaka");
SELECT * FROM Products WHERE ProductName LIKE "G%" AND Price > 20;
SELECT distinct Country FROM Suppliers;
SELECT count(ProductID) FROM Products WHERE ProductName LIKE "%od%";
SELECT avg(Price) FROM Products WHERE Unit LIKE "%bottles%";
SELECT CustomerName FROM Customers WHERE Country NOT IN ("Brasil", "Mexico");
SELECT FirstName, LastName FROM Employees WHERE BirthDate > "1960-01-01";
SELECT * FROM Products WHERE Price = 10 union SELECT * FROM Products WHERE Price = 13 union SELECT * FROM Products WHERE Price =15;
SELECT Orders.OrderID, Shippers.ShipperName FROM Orders LEFT JOIN Shippers ON Orders.ShipperID = Shippers.ShipperID;
SELECT Employees.FirstName, Employees.LastName, Orders.OrderDate FROM Employees INNER JOIN Orders ON Employees.EmployeeID = Orders.EmployeeID WHERE Orders.OrderDate = "1996-11-27";
SELECT FirstName, LastName FROM Employees WHERE EmployeeID IN (SELECT EmployeeID FROM Orders WHERE OrderDate = "1996-11-27");
SELECT Products.ProductName, Products.Price, Suppliers.SupplierName FROM Products JOIN Suppliers ON Products.SupplierID = Suppliers.SupplierID WHERE Suppliers.SupplierName = "Grandma Kelly's Homestead" AND Products.Price >27;
SELECT sum(OrderDetails.Quantity), Products.ProductName FROM OrderDetails INNER JOIN Products ON OrderDetails.ProductID = Products.ProductID WHERE Products.ProductName = "Queso Cabrales";
SELECT sum(OrderDetails.Quantity) FROM OrderDetails WHERE ProductID IN (SELECT ProductID FROM Products WHERE ProductName = 'Queso Cabrales');
SELECT Orders.OrderID, Customers.CustomerName, Employees.FirstName, Employees.LastName FROM Orders LEFT JOIN Customers ON Orders.CustomerID = Customers.CustomerID LEFT JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID;
SELECT Orders.OrderID, Customers.CustomerName, Concat(Employees.FirstName, " ", Employees.LastName) AS EmployeeName FROM Orders LEFT JOIN Customers ON Orders.CustomerID = Customers.CustomerID LEFT JOIN Employees ON Orders.EmployeeID = Employees.EmployeeID;
SELECT Products.ProductName, Products.CategoryID, Orders.CustomerID, Customers.CustomerName FROM Products JOIN Customers ON Products.CategoryID = Customers.CustomerID JOIN Orders ON Customers.CustomerID = Orders.CustomerID WHERE Customers.CustomerName = "Blondel père et fils";